### ISSUE TITLE
Feature request: JavaScript (.js) config file

### ISSUE THREAD

**Issue by mcous** [develar/read-config-file#3]
Hello, and first off, I really appreciate the `electron-builder` project and wanted to thank you for all the time and energy you've put into it.

I came across this `read-config-file` package because it appears to be the settings loading package for `electron-builder`. For work, I help maintain [an application](https://github.com/Opentrons/opentrons/tree/v3a/app-shell) that uses `electron-builder` to create its packages. Reading through the publish and auto-update guides, I'm finding myself thinking that it would be useful if I could define my configuration in `.js` rather than JSON, YAML, etc.

Specifically, I'm looking to adjust my configuration based on CI environment (Are we in CI? Is this a tagged commit? etc.), and to do so in JavaScript would be convenient. Many JS tools, like [webpack](https://webpack.js.org/concepts/configuration/) and [eslint](https://eslint.org/docs/user-guide/configuring#configuration-file-formats) default to / allow for a `.js` file with `module.exports = configObject` as their configuration file. It would be cool if `electron-builder` did so, too, and I'd be happy to help and/or open a PR into this package to add that feature.

**Comment by develar** [comment]
You can use electron-builder programmatically. https://github.com/electron-userland/electron-builder#programmatic-usage Is it solution for you?

**Comment by mcous** [comment]
Yes, a custom build script using the electron-builder API would likely work, but I haven't had the time to spend researching / building it. I ended up working around _most_ of my desired functionality with a combination of `make`, environment variables, fields that accept [file macros](https://www.electron.build/file-patterns#file-macros), and the `--config.subconfig` CLI args. I still have issues with certain fields where I can't use the file macros (see electron-userland/electron-builder#2963), but I can live with those limitations for the time being.

I use lerna for a few projects, and it depends on [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) to load config files. This feature request is based on the functionality I've seen there.

**Comment by AoDev** [comment]
@mcous I have sent a PR for this just now. https://github.com/develar/read-config-file/pull/5
